version: '3'

tasks:
  build:
    cmds:
      - go build -o ./bin/fontman ./cmd/fontman
  lint:
    cmds:
      - gofmt -w . 
  test:
    cmds:
      - go test .
  run:
    cmds:
      - task lint
      - task build
      - ./bin/fontman {{.CLI_ARGS}}
